
mode:
  # - train
  - test
training_params:
  T: 1
  alpha: 0.05
  number_episodes: 100
  save_folder: "phase2"
  train_plot_title: "Phase 2"
  window_size: 2
  

env:
  agents_num: 10
  waypoints_num: 0
  obstacles_num: 80
  update_waypoint: False
  x_size: 100
  y_size: 100
  max_dist: 5
  spawn_center_x: 50
  spawn_center_y: 50
  timeout: 200
  agent_speed: 0.2

active_modules:
  COH:
    discount: 0.01
    # thresh: 3
    w: 0.3
    Qmatrix_path : "results/phase2/Qmatrix_99.npy"
  ALN:
    discount: 0.01
    # thresh: 3
    w: 0.1
    Qmatrix_path : "results/phase2/Qmatrix_99.npy"
  COL:
    discount: 0.0
    away_thresh: 1.5
    close_thresh: 0.2
    w: 0.3
    Qmatrix_path : "results/phase2/Qmatrix_99.npy"
  OBS:
    discount: 0.7
    away_thresh: 2.0
    close_thresh: 0.4
    w: 0.3
    Qmatrix_path : "results/phase2/Qmatrix_99.npy"
  


