
mode:
  - train
training_params:
  T: 3
  alpha: 0.01
  number_episodes: 1000
  save_folder: "phase2"
  train_plot_title: "Phase 2"
  window_size: 20
  termination_reward: 0
  timeout: 10000

env:
  agents_num: 10
  waypoints_num: 0
  obstacles_num: 50
  update_waypoint: False
  x_size: 75
  y_size: 375
  max_dist: 5
  spawn_center_x: 10
  spawn_center_y: 10

active_modules:
  COH:
    discount: 0.01
    # thresh: 3
    w: 0.166667
  ALN:
    discount: 0.01
    # thresh: 3
    w: 0.166667
  COL:
    discount: 0.0
    away_thresh: 1.5
    close_thresh: 0.2
    w: 0.3333
  OBS:
    discount: 0.7
    away_thresh: 3.0
    close_thresh: 1.0
    w: 0.3333


