
mode:
  # - train
  - test
training_params:
  T: 1
  alpha: 0.1
  number_episodes: 1000
  save_folder: "phase3"
  train_plot_title: "Phase 3"
  window_size: 20
  

env:
  agents_num: 10
  waypoints_num: 3
  obstacles_num: 10
  update_waypoint: True
  waypoint_dist_thresh: 3.0
  # waypoint_in_radius: 10
  x_size: 100
  y_size: 100
  max_dist: 5
  spawn_center_x: 30
  spawn_center_y: 30
  timeout: 1000
  agent_speed: 1.0

active_modules:
  TGT:
      discount: 0.9
      thresh: 3.0
      w: 0.75
      # Qmatrix_path : "results/phase1/Qmatrix_19999.npy"
      Qmatrix_path: "results/phase3/Qmatrix_359.npy"
  COH:
    discount: 0.01
    # thresh: 3
    w: 0.15
    # Qmatrix_path : "results/phase2/Qmatrix_99.npy"
    Qmatrix_path: "results/phase3/Qmatrix_359.npy"
  ALN:
    discount: 0.01
    # thresh: 3
    w: 0.0005
    # Qmatrix_path : "results/phase2/Qmatrix_99.npy"
    Qmatrix_path: "results/phase3/Qmatrix_359.npy"
  COL:
    discount: 0.0
    away_thresh: 1.5
    close_thresh: 0.2
    w: 0.05
    # Qmatrix_path : "results/phase2/Qmatrix_99.npy"
    Qmatrix_path: "results/phase3/Qmatrix_359.npy"
  OBS:
    discount: 0.7
    away_thresh: 3.0
    close_thresh: 1.0
    w: 0.05
    # Qmatrix_path : "results/phase2/Qmatrix_99.npy"
    Qmatrix_path: "results/phase3/Qmatrix_359.npy"
  


